"""
Configuration & Schema Mapping
===============================
This is the SINGLE SOURCE OF TRUTH for the entire application.
1. Put the CSV files in the DATA_DIR.
2. Update the table/column names in this file.
Nothing else in the codebase needs to be rewritten.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# Data Directory
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

# -------------------------------------------------------------
# TABLE & COLUMN MAPPINGS
# (Edit here tomorrow when real schema drops)
# -------------------------------------------------------------
TABLE_VENDORS = "vendors"
TABLE_PAYOUTS = "vendor_payouts"
TABLE_TRANSACTIONS = "transactions"
TABLE_RECONCILIATION = "reconciliation_status"
TABLE_ACCOUNTS = "chart_of_accounts"

SCHEMA_CONFIG = {
    "vendors": {
        "file": "vendor_list.csv",
        "id_col": "vendor_id", #we can change col names here directly instead of changing in everywhere 
        "name_col": "vendor_name",
        "category_col": "category"
    },
    "vendor_payouts": {
        "file": "vendor_payouts.csv",
        "id_col": "payout_id",
        "date_col": "payout_date",
        "vendor_id_col": "vendor_id",
        "amount_col": "amount",
        "currency_col": "currency",
        "status_col": "status",
        "desc_col": "description"
    },
    "transactions": {
        "file": "transactions.csv",
        "id_col": "transaction_id",
        "date_col": "transaction_date",
        "vendor_id_col": "vendor_id",
        "account_id_col": "account_id",
        "amount_col": "amount",
        "type_col": "transaction_type",
        "payout_id_col": "payout_id",
        "desc_col": "description"
    },
    "reconciliation_status": {
        "file": "reconciliation_status.csv",
        "txn_id_col": "transaction_id",
        "status_col": "reconciliation_status",
        "date_col": "reconciled_date",
        "notes_col": "notes"
    },
    "chart_of_accounts": {
        "file": "chart_of_accounts.csv",
        "id_col": "account_id",
        "name_col": "account_name",
        "type_col": "account_type"
    }
}

# -------------------------------------------------------------
# RECONCILIATION STATUS MAPPINGS
# (Trap #5: Handle non-binary states)
# -------------------------------------------------------------
RECONCILIATION_VALUES = {
    "reconciled": ["reconciled", "matched"],
    "unreconciled": ["unreconciled", "unmatched"],
    "pending": ["pending", "in_review", "awaiting confirmation"],
    "disputed": ["disputed", "flagged", "failed"]
}

# -------------------------------------------------------------
# VENDOR ALIASES & ACRONYM OVERRIDES
# Note: Acronyms (e.g. AWS -> Amazon Web Services) are dynamically
# generated by resolver.py. Add custom domain overrides here.
# -------------------------------------------------------------
VENDOR_ALIASES = {
    "google": "Google Cloud Platform",
}

# -------------------------------------------------------------
# MODEL CONFIGURATION (Groq Engine)
# Dedicated Model: openai/gpt-oss-120b
# -------------------------------------------------------------
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
ACTIVE_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
